### ISSUE TITLE
Connection to Elasticsearch fails (1.7)

### ISSUE THREAD

**Issue by moooji** [simianhacker/bunyan-elasticsearch#4]
This is fixed here: https://github.com/simianhacker/bunyan-elasticsearch/pull/3

**Comment by moooji** [comment]
What do you think about the PR? Will you merge it?

**Comment by Trozz** [comment]
@simianhacker ?

**Comment by reesew** [comment]
@simianhacker bump

**Comment by thalesfsp** [comment]
@moooji @Trozz @reesew ping

**Comment by Trozz** [comment]
@thalesfsp pong

**Comment by thalesfsp** [comment]
@moooji @Trozz @reesew Closing issue, PR already merged ;)
