### ISSUE TITLE
Updated NPM

### ISSUE THREAD

**Issue by Trozz** [simianhacker/bunyan-elasticsearch#5]
I have forked this repo and have setup a updated package on npmjs.

https://www.npmjs.com/package/bunyan-elasticsearch-updated

when @simianhacker comes back we can look at merging the up to date copy of package.json

**Comment by thalesfsp** [comment]
@Trozz, closing, dependencies already up-to-date, thanks ;)

**Comment by Trozz** [comment]
ty :)
